spring.application.name=config-server
# Habilita o Config Server
server.port=8888
# Configuração para usar o backend nativo (file system)
spring.profiles.active=native
# O caminho é relativo ao diretório onde o config-server está sendo executado.
spring.cloud.config.server.native.search-locations=file:./config-repo/
# Configuração para Demonstração de Segurança (D):
spring.cloud.config.server.encrypt.key=UMA_CHAVE_SECRETA_FORTE_PARA_CRIPTO